In [1]:
import pandas as pd
import plotly.express as px
from datetime import datetime

In [2]:
metadata_path = '../../config/metadata.tsv'
bed_targets_path = '../../config/ag-vampir.bed'
wkdir = '../..'
dataset= "my_dataset_name"
panel= 'ag-vampir'
platform='illumina'
cohort_cols = 'taxon,location'
config_path = '../../config/config.yaml'

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("max_colwidth", None)

In [3]:
# Parameters
config_path = "config/config.yaml"
metadata_path = "results/config/metadata.tsv"
bed_targets_path = "config/af-vampir.bed"
panel = "Afairy"
dataset = "Afairy"
platform = "nanopore"
cohort_cols = "cohort"
wkdir = "/mnt/user_shares/namulil/lstm_scratch/local_scratch/ampseeker_run"

# Run information

In [4]:
time = datetime.today().strftime('%Y-%m-%d %H:%M:%S')

print(f"Dataset: {dataset}\nPanel: {panel}\nPlatform: {platform}\nCohort columns: {cohort_cols}\n\nExecution time: {time}")

Dataset: Afairy
Panel: Afairy
Platform: nanopore
Cohort columns: cohort

Execution time: 2025-12-07 20:38:31

#### Reference genome

In [5]:
import yaml 
with open(config_path, 'r') as file:
    config_yml = yaml.safe_load(file)

ref_dict = {k:v for k,v in config_yml.items() if 'reference' in k}

ref_df = pd.DataFrame.from_dict(ref_dict, orient='index').reset_index()
ref_df.columns = ['reference', 'value']
ref_df

,reference,value
0,reference-fasta,resources/reference/VectorBase-68_AfunestusAfunGA1_Genome.fasta
1,reference-gff3,resources/reference/VectorBase-68_AfunestusAfunGA1.gff
2,reference-snpeffdb,mysnpeffdb

#### Panel information

In [6]:
import sys
import os
sys.path.append(os.path.join(wkdir, 'workflow'))
import ampseekertools as amp

panel_metadata = amp.load_bed(bed_targets_path)
contigs = panel_metadata.contig.unique()
panel_metadata

         contig     start       end amplicon_id    mutation  ref  alt
0   AfunGA1_2RL   8672966   8672967     Cyp6aa1     Cyp6aa1    A    C
1   AfunGA1_2RL   8675311   8675312     Cyp6aa2     Cyp6aa2    G    T
2   AfunGA1_2RL   8682921   8682922     Cyp6a13     Cyp6a13  NaN  NaN
3   AfunGA1_2RL   8686614   8686615     Cyp6P9a     Cyp6P9a  NaN  NaN
4   AfunGA1_2RL   8689257   8689258     Cyp6P9b     Cyp6P9b  NaN  NaN
5   AfunGA1_2RL   8692006   8692007    Cyp6a14b    Cyp6a14b  NaN  NaN
6   AfunGA1_2RL   8695367   8695368      Cyp6a8      Cyp6a8  NaN  NaN
7   AfunGA1_2RL   8704764   8704765     Cyp6ad1     Cyp6ad1  NaN  NaN
8   AfunGA1_2RL  76406604  76406605     Gste1_2     Gste1_2  NaN  NaN
9   AfunGA1_2RL  76404165  76404166     Gste3_7     Gste3_7  NaN  NaN
10  AfunGA1_2RL  76411071  76411072       Gste6       Gste6  NaN  NaN
11  AfunGA1_2RL  76408777  76408778       Gste4       Gste4  NaN  NaN
12  AfunGA1_2RL  88729989  88729990      Cyp6R1      Cyp6R1  NaN  NaN
13  AfunGA1_2RL  88707321  88707322      Cyp6M8      Cyp6M8  NaN  NaN
14  AfunGA1_2RL  88704314  88704315      Cyp6M7      Cyp6M7  NaN  NaN
15  AfunGA1_2RL  88701977  88701978      Cyp6M4      Cyp6M4  NaN  NaN
16  AfunGA1_2RL  88664974  88664975      Cyp6Z3      Cyp6Z3  NaN  NaN
17  AfunGA1_2RL  88662627  88662628      Cyp6Z1      Cyp6Z1  NaN  NaN
18    AfunGA1_X   8449682   8449683      Cyp9k1      Cyp9k1  NaN  NaN
19    AfunGA1_X  13659411  13659412       DGK_1       DGK_1  NaN  NaN
20  AfunGA1_3RL  67913210  67913211         TMC         TMC  NaN  NaN
21  AfunGA1_3RL  44125475  44125476   Vgsc_976F   Vgsc_976F  NaN  NaN
22  AfunGA1_3RL  44116128  44116129  Vgsc_1842S  Vgsc_1842S  NaN  NaN
23  AfunGA1_3RL  13549227  13549228         Rdl         Rdl  NaN  NaN
24  AfunGA1_2RL  19481500  19481501        Ace1        Ace1  NaN  NaN
25  AfunGA1_2RL  89597248  89597249         ASL         ASL  NaN  NaN
26  AfunGA1_2RL  99503339  99503340      Cyp9M1      Cyp9M1  NaN  NaN
27    AfunGA1_X  13573760  13573761       Dgk_2       Dgk_2  NaN  NaN
28  AfunGA1_3RL  30595648  30595649     Coeae1f     Coeae1f  NaN  NaN
29  AfunGA1_3RL  30598241  30598242     Coeae2f     Coeae2f    G    T

#### Input metadata

In [7]:
# load panel metadata
if metadata_path.endswith('.xlsx'):
    metadata = pd.read_excel(metadata_path, engine='openpyxl')
elif metadata_path.endswith('.tsv'):
    metadata = pd.read_csv(metadata_path, sep="\t")
elif metadata_path.endswith('.csv'):
    metadata = pd.read_csv(metadata_path, sep=",")
else:
    raise ValueError("Metadata file must be .xlsx or .csv")

metadata

    sample_id cohort                                               fq1
0   barcode01   fang  resources/reads/ONT_OPT/fastq/barcode01.fastq.gz
1   barcode02   fang  resources/reads/ONT_OPT/fastq/barcode02.fastq.gz
2   barcode03   fang  resources/reads/ONT_OPT/fastq/barcode03.fastq.gz
3   barcode04   fang  resources/reads/ONT_OPT/fastq/barcode04.fastq.gz
4   barcode05   fang  resources/reads/ONT_OPT/fastq/barcode05.fastq.gz
5   barcode06   fang  resources/reads/ONT_OPT/fastq/barcode06.fastq.gz
6   barcode07   fang  resources/reads/ONT_OPT/fastq/barcode07.fastq.gz
7   barcode08   fang  resources/reads/ONT_OPT/fastq/barcode08.fastq.gz
8   barcode09   fang  resources/reads/ONT_OPT/fastq/barcode09.fastq.gz
9   barcode10   fang  resources/reads/ONT_OPT/fastq/barcode10.fastq.gz
10  barcode11   fang  resources/reads/ONT_OPT/fastq/barcode11.fastq.gz
11  barcode12   fang  resources/reads/ONT_OPT/fastq/barcode12.fastq.gz
12  barcode13   fang  resources/reads/ONT_OPT/fastq/barcode13.fastq.gz
13  barcode14   fang  resources/reads/ONT_OPT/fastq/barcode14.fastq.gz
14  barcode15   fang  resources/reads/ONT_OPT/fastq/barcode15.fastq.gz
15  barcode16   fang  resources/reads/ONT_OPT/fastq/barcode16.fastq.gz
16  barcode17   fang  resources/reads/ONT_OPT/fastq/barcode17.fastq.gz
17  barcode18   fang  resources/reads/ONT_OPT/fastq/barcode18.fastq.gz
18  barcode19   fang  resources/reads/ONT_OPT/fastq/barcode19.fastq.gz
19  barcode20   fang  resources/reads/ONT_OPT/fastq/barcode20.fastq.gz
20  barcode21   fang  resources/reads/ONT_OPT/fastq/barcode21.fastq.gz
21  barcode22   fang  resources/reads/ONT_OPT/fastq/barcode22.fastq.gz
22  barcode23   fang  resources/reads/ONT_OPT/fastq/barcode23.fastq.gz
23  barcode24   fang  resources/reads/ONT_OPT/fastq/barcode24.fastq.gz
24  barcode25   fang  resources/reads/ONT_OPT/fastq/barcode25.fastq.gz
25  barcode26   fang  resources/reads/ONT_OPT/fastq/barcode26.fastq.gz
26  barcode27   fang  resources/reads/ONT_OPT/fastq/barcode27.fastq.gz
27  barcode28   fang  resources/reads/ONT_OPT/fastq/barcode28.fastq.gz
28  barcode29   fang  resources/reads/ONT_OPT/fastq/barcode29.fastq.gz
29  barcode30   fang  resources/reads/ONT_OPT/fastq/barcode30.fastq.gz
30  barcode31  fumoz  resources/reads/ONT_OPT/fastq/barcode31.fastq.gz
31  barcode32  fumoz  resources/reads/ONT_OPT/fastq/barcode32.fastq.gz
32  barcode33  fumoz  resources/reads/ONT_OPT/fastq/barcode33.fastq.gz
33  barcode34  fumoz  resources/reads/ONT_OPT/fastq/barcode34.fastq.gz
34  barcode35  fumoz  resources/reads/ONT_OPT/fastq/barcode35.fastq.gz
35  barcode36  fumoz  resources/reads/ONT_OPT/fastq/barcode36.fastq.gz
36  barcode37  fumoz  resources/reads/ONT_OPT/fastq/barcode37.fastq.gz
37  barcode38  fumoz  resources/reads/ONT_OPT/fastq/barcode38.fastq.gz
38  barcode39  fumoz  resources/reads/ONT_OPT/fastq/barcode39.fastq.gz
39  barcode40  fumoz  resources/reads/ONT_OPT/fastq/barcode40.fastq.gz
40  barcode41  fumoz  resources/reads/ONT_OPT/fastq/barcode41.fastq.gz
41  barcode42  fumoz  resources/reads/ONT_OPT/fastq/barcode42.fastq.gz
42  barcode43  fumoz  resources/reads/ONT_OPT/fastq/barcode43.fastq.gz
43  barcode44  fumoz  resources/reads/ONT_OPT/fastq/barcode44.fastq.gz
44  barcode45  fumoz  resources/reads/ONT_OPT/fastq/barcode45.fastq.gz
45  barcode46  fumoz  resources/reads/ONT_OPT/fastq/barcode46.fastq.gz
46  barcode47  fumoz  resources/reads/ONT_OPT/fastq/barcode47.fastq.gz
47  barcode48  fumoz  resources/reads/ONT_OPT/fastq/barcode48.fastq.gz
48  barcode49  fumoz  resources/reads/ONT_OPT/fastq/barcode49.fastq.gz
49  barcode50  fumoz  resources/reads/ONT_OPT/fastq/barcode50.fastq.gz
50  barcode51  fumoz  resources/reads/ONT_OPT/fastq/barcode51.fastq.gz
51  barcode52  fumoz  resources/reads/ONT_OPT/fastq/barcode52.fastq.gz
52  barcode53  fumoz  resources/reads/ONT_OPT/fastq/barcode53.fastq.gz
53  barcode54  fumoz  resources/reads/ONT_OPT/fastq/barcode54.fastq.gz
54  barcode55  fumoz  resources/reads/ONT_OPT/fastq/barcode55.fastq.gz
55  barcode56  fumoz  resources/reads/ONT_OPT/fastq/barcode56.fastq.gz
56  barcode57  fumoz  resources/reads/ONT_OPT/fastq/barcode57.fastq.gz
57  barcode58  fumoz  resources/reads/ONT_OPT/fastq/barcode58.fastq.gz
58  barcode59  fumoz  resources/reads/ONT_OPT/fastq/barcode59.fastq.gz
59  barcode60  fumoz  resources/reads/ONT_OPT/fastq/barcode60.fastq.gz
60  barcode61  field  resources/reads/ONT_OPT/fastq/barcode61.fastq.gz
61  barcode62  field  resources/reads/ONT_OPT/fastq/barcode62.fastq.gz
62  barcode63  field  resources/reads/ONT_OPT/fastq/barcode63.fastq.gz
63  barcode64  field  resources/reads/ONT_OPT/fastq/barcode64.fastq.gz
64  barcode65  field  resources/reads/ONT_OPT/fastq/barcode65.fastq.gz
65  barcode66  field  resources/reads/ONT_OPT/fastq/barcode66.fastq.gz
66  barcode67  field  resources/reads/ONT_OPT/fastq/barcode67.fastq.gz
67  barcode68  field  resources/reads/ONT_OPT/fastq/barcode68.fastq.gz
68  barcode69  field  resources/reads/ONT_OPT/fastq/barcode69.fastq.gz
69  barcode70  field  resources/reads/ONT_OPT/fastq/barcode70.fastq.gz
70  barcode71  field  resources/reads/ONT_OPT/fastq/barcode71.fastq.gz
71  barcode72  field  resources/reads/ONT_OPT/fastq/barcode72.fastq.gz
72  barcode73  field  resources/reads/ONT_OPT/fastq/barcode73.fastq.gz
73  barcode74  field  resources/reads/ONT_OPT/fastq/barcode74.fastq.gz
74  barcode75  field  resources/reads/ONT_OPT/fastq/barcode75.fastq.gz
75  barcode76  field  resources/reads/ONT_OPT/fastq/barcode76.fastq.gz
76  barcode77  field  resources/reads/ONT_OPT/fastq/barcode77.fastq.gz
77  barcode78  field  resources/reads/ONT_OPT/fastq/barcode78.fastq.gz
78  barcode79  field  resources/reads/ONT_OPT/fastq/barcode79.fastq.gz
79  barcode80  field  resources/reads/ONT_OPT/fastq/barcode80.fastq.gz
80  barcode81  field  resources/reads/ONT_OPT/fastq/barcode81.fastq.gz
81  barcode82  field  resources/reads/ONT_OPT/fastq/barcode82.fastq.gz
82  barcode83  field  resources/reads/ONT_OPT/fastq/barcode83.fastq.gz
83  barcode84  field  resources/reads/ONT_OPT/fastq/barcode84.fastq.gz
84  barcode85  field  resources/reads/ONT_OPT/fastq/barcode85.fastq.gz
85  barcode86  field  resources/reads/ONT_OPT/fastq/barcode86.fastq.gz
86  barcode87  field  resources/reads/ONT_OPT/fastq/barcode87.fastq.gz
87  barcode88  field  resources/reads/ONT_OPT/fastq/barcode88.fastq.gz
88  barcode89  field  resources/reads/ONT_OPT/fastq/barcode89.fastq.gz
89  barcode90  field  resources/reads/ONT_OPT/fastq/barcode90.fastq.gz
90  barcode91  field  resources/reads/ONT_OPT/fastq/barcode91.fastq.gz
91  barcode92  field  resources/reads/ONT_OPT/fastq/barcode92.fastq.gz
92  barcode93  field  resources/reads/ONT_OPT/fastq/barcode93.fastq.gz
93  barcode94  field  resources/reads/ONT_OPT/fastq/barcode94.fastq.gz
94  barcode95  field  resources/reads/ONT_OPT/fastq/barcode95.fastq.gz
95  barcode96  field  resources/reads/ONT_OPT/fastq/barcode96.fastq.gz